version: '3.8'

services:
  # ğŸŒ API principal - DEVELOP
  gescomph-api-develop:
    container_name: gescomph-api-develop
    build:
      context: ../..
      dockerfile: WebGESCOMPH/Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      - gescomph-sqlserver-develop
    ports:
      - "5100:8080"
    networks:
      - gescomph_network
    labels:
      - com.gescomph.environment=develop

# ==============================
# ğŸ“¦ redes
# ==============================

networks:
  gescomph_network:
    driver: bridge
